const toppings = [
  {
    name: "Capsicum",
    price: 1.2,
    qty: 2,
    desc: "a short bio o",
    image: "https://picsum.photos/200/300.webp",
    check: false,
    color: "blue",
    size: "41",
  },
  {
    name: "Paneer",
    price: 2.0,
    qty: 1,
    desc: "a short bio o",
    image: "https://picsum.photos/200/300.webp",
    check: false,
    color: "blue",
    size: "41",
  },
  {
    name: "Red Paprika",
    price: 2.5,
    qty: 1,
    desc: "a short bio o",
    image: "https://picsum.photos/200/300.webp",
    check: false,
    color: "blue",
    size: "41",
  },
  {
    name: "Onions",
    price: 3.0,
    qty: 1,
    desc: "a short bio o",
    image: "https://picsum.photos/200/300.webp",
    check: false,
    color: "blue",
    size: "41",
  },
  {
    name: "Extra Cheese",
    price: 3.5,
    qty: 1,
    desc: "a short bio o",
    image: "https://picsum.photos/200/300.webp",
    check: false,
    color: "blue",
    size: "41",
  },
  {
    name: "Baby Corns",
    price: 3.0,
    qty: 1,
    desc: "a short bio o",
    image: "https://picsum.photos/200/300.webp",
    check: false,
    color: "blue",
    size: "41",
  },
  {
    name: "Mushroom",
    price: 2.0,
    qty: 1,
    desc: "a short bio o",
    image: "https://picsum.photos/200/300.webp",
    check: false,
    color: "blue",
    size: "41",
  },
];

export default toppings;
